name: 'Label Actions'
description: 'Perform actions when issues, pull requests or discussions are labeled or unlabeled'
author: 'Armin Sebastian'
inputs:
  github-token:
    description: 'GitHub access token'
    default: '${{ github.token }}'
  config-path:
    description: 'Configuration file path'
    default: '.github/label-actions.yml'
  process-only:
    description: 'Process label events only for issues, pull requests or discussions, value must be a comma separated list, list items must be one of `issues`, `prs` or `discussions`'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
