name: Create release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Get release information
        id: release_info
        run: |
          echo ::setOutput name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::setOutput name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Create GitHub release
        uses: Ludy87/action-gh-release@master
        with:
          tag_name: ${{ steps.release_info.outputs.TAG }}
          name: ${{ steps.release_info.outputs.TAG }}
          body: >
            Learn more about this release from the [changelog](https://github.com/dessant/label-actions/blob/master/CHANGELOG.md#changelog).
